GET http://localhost:3004/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR1YW5lZ2FkYW1hQGdtYWlsLmNvbSIsImlkIjoiNjZhMmI0NzVmOGVmNGQzNTMyM2ZkMDc2IiwiaWF0IjoxNzIyMDcyNTA0fQ.L6NiF7iMw27wx5GYxzse58rw0hxU1JCfGbIjcGpOxvQ